from setuptools import setup, find_packages

setup(
    name="shortfactory-langchain",
    version="0.1.0",
    description="AI Video Content Production using LangChain",
    author="ShortFactory Team",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.8",
    install_requires=[
        "langchain",
        "langchain-core",
        "langchain-google-genai",
        "python-dotenv",
        "google-generativeai",
        "jupyter",
        "requests",
        "openai",
        "moviepy",
        "gTTS",
        "pydub",
        "Pillow",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ],
)
